config = {
    'name': '',
    'format': 'mp4',
    'font': 'kaiti.ttf',
    'bgm': '',
    'bgImg': '',
    'size': [1280, 768],
    'fps': 30,
    'sr': 22050,
    'padding': 0,
    'contents': [],
    'header': '', 
    'footer': '',
    'external': '',
    # 爬虫模块配置
    'crawler': {},
    # PaddleSpeech 配置
    'tts': {},
    'resizeMode': 'wrap',
    'subtitleMaxLen': 50,
    'assetDir': None,
    'ttsVoice': 'zh-CN-XiaoyiNeural',
    'ttsVolume': '+0%',
    'ttsRate': '-10%',
}